### ISSUE TITLE
[8.0][9.0] Orange pointer dot trailing pan/zoom

### ISSUE THREAD

**Issue by pankk** [OCA/geospatial#122]
The orange dot on the geolocalization map view follows the direction of panning and zooming. I can reproduce this when using Chrome across local, runbot 8.0 and runbot 9.0. When using Firefox I do not have this issue. This issue also does not seem present on http://www.openstreetmap.org/ neither on Chrome nor Firefox. (Maybe updating Mapfish or something else in the static directory would fix this.)

**Comment by pedrobaeza** [comment]
Can you include a screenshot of the problem?

**Comment by pankk** [comment]
<img width="443" alt="geo1" src="https://cloud.githubusercontent.com/assets/3942631/19524518/4df3d8ee-961e-11e6-91f3-aa69e4b86f17.PNG">
<img width="402" alt="geo2" src="https://cloud.githubusercontent.com/assets/3942631/19524517/4de9a13a-961e-11e6-8f4c-110e2218fcee.PNG">

Here are the screenshots. The first image is probably correct, the second is obtained by panning to the east. As you can see the orange dot has been displaced into the river.

**Comment by pedrobaeza** [comment]
Thanks for the info

@yvaucher, any clue?

**Comment by sciallo** [comment]
is your browser zoom in or out? You could be looking at issue #82

**Comment by pankk** [comment]
@sciallo, thanks, I actually overlooked that issue. But after doublechecking my browser is at normal zoom levels. Can someone else check if they can reproduce this on runbot? It could still be a weird combination of my Chrome version, OS, and display setup (resolution):  53.0.2785.143 m, Windows 10, 1920x1080 on two displays (extended), respectively.

**Comment by yvaucher** [comment]
Most of offset issue should have been fixed in 9.0 with https://github.com/OCA/geospatial/pull/88
As @sciallo pointed out there is a bug with zoom in Chrome that couldn't be fixed.

About version 8.0 I backported the fix not long time ago: https://github.com/OCA/geospatial/commit/d7c8dc082db254c43db262ff2c01fd31361504a2

I can't test it on Chrome + Windows 10
I just checked again on 8.0 version of runbot on Chrome + Ubuntu 16.04 and I only have this issue when browser zoom is not 100% as "expected".

You might want to switch to OL3: https://github.com/OCA/geospatial/pull/121
