### ISSUE TITLE
[8.0] Error in the map in a tab of notebook

### ISSUE THREAD

**Issue by josemicopa** [OCA/geospatial#125]
If i change to the edit mode not being in the map tab at change to the map tab appears as follow
![seleccion_003](https://cloud.githubusercontent.com/assets/23212280/21216891/948d091c-c2a9-11e6-946e-b26c3fae7cb1.png)

**Comment by yvaucher** [comment]
@joseodoo Could you tell us on which version of Odoo ?

**Comment by josemicopa** [comment]
@yvaucher I am developing for Odoo 8

**Comment by yvaucher** [comment]
@joseodoo there was multiple issues with map in tabs resolved in version 9.0

https://github.com/OCA/geospatial/pull/78
https://github.com/OCA/geospatial/pull/99

It might be that your map is initialized with a wrong size because the container is in an invisible tab.
I would not recommend to use a map under tabs in version 8.0 unless you patch it.
