### ISSUE TITLE
Geoengine and multicompany

### ISSUE THREAD

**Issue by Deliveriya** [OCA/geospatial#139]
Odoo 8.0
The system is used with the multicompany option.
In the event that a user has a company_id other than the company_id superuser (Administrator), an error occurs

`AccessError: ('AccessError', u'The requested operation can not be completed due to security restrictions.) Please contact your system administrator. \ N \ n (Document type: res.users, Operation: read) ')`

The user can not create a new client. I revised the permissions to res_company, res_users, res_partner, and access rules, there are no errors.

If you exclude in geoengine_base_geolocalize / models / res_partner.py the compute = '_ get_geo_point' coordinate calculation, the error does not occur, but the maps no longer display the coordinates.

```
    Geo_point = geo_fields.GeoPoint (
        Readonly = True, store = True, compute = '_ get_geo_point')
```
To
```
    Geo_point = geo_fields.GeoPoint (
        Readonly = True, store = True)

```

How to fix?

Full stack trace https://yadi.sk/i/js_8i3Uq3HgUi4

**Comment by yvaucher** [comment]
This is certainly due to the record rules used for multi company, saying to you that at some point the code wants to read a user of a different company than your current user.

Maybe you can trace it down with a pdb to get at which point it fails trying to read a user of the other company. Maybe an issue with the triggers. Maybe try by removing the `api.depends()` to see if the triggers are the problem.

**Comment by Deliveriya** [comment]
You are right, when you remove decorator @api.depends ('partner_latitude', 'partner_longitude'), there is no error when creating customer. Tried to debug (see attach).

db1=# select name, company_id from res_partner where id = 488; 
name | company_id
------+------------
(0 rows) 
db1=# 

Are we trying to set record values that does not exist? 
When updating partner records, an error does not occur.   
![2017-05-08_19-52-37](https://cloud.githubusercontent.com/assets/26636805/25818401/2b75ae92-3433-11e7-972e-5316e2e147fc.png)
![2017-05-08_21-10-03](https://cloud.githubusercontent.com/assets/26636805/25818404/2f4550ea-3433-11e7-9453-f003138cb488.png)

**Comment by yvaucher** [comment]
I don't see any attachment here in github.

With `pdb` I meant python debugger.

@lmignon did you had the chance to use your module in a multicompany env ?

**Comment by Deliveriya** [comment]
Yes, I understand.I uploaded attachments on github. See above.

**Comment by Deliveriya** [comment]
>` /usr/lib/python2.7/dist-packages/openerp/addons/geoengine_base_geolocalize/models/res_partner.py(95)_get_geo_point()
     94         ipdb.set_trace()
---> 95         if not self.partner_latitude or not self.partner_longitude:
     96             self.geo_point = False

ipdb> n
> /usr/lib/python2.7/dist-packages/openerp/addons/geoengine_base_geolocalize/models/res_partner.py(96)_get_geo_point()
     95         if not self.partner_latitude or not self.partner_longitude:
---> 96             self.geo_point = False
     97         else:

ipdb> n
AccessError: AccessEr...: read)')
> /usr/lib/python2.7/dist-packages/openerp/addons/geoengine_base_geolocalize/models/res_partner.py(96)_get_geo_point()
     95         if not self.partner_latitude or not self.partner_longitude:
---> 96             self.geo_point = False
     97         else:

ipdb> n
--Return--
None
> /usr/lib/python2.7/dist-packages/openerp/addons/geoengine_base_geolocalize/models/res_partner.py(96)_get_geo_point()
     95         if not self.partner_latitude or not self.partner_longitude:
---> 96             self.geo_point = False
     97         else:

ipdb> n
AccessError: AccessEr...: read)')
> /usr/lib/python2.7/dist-packages/openerp/api.py(443)new_api()
    442     def new_api(self, *args, **kwargs):
--> 443         result = [method(rec, *args, **kwargs) for rec in self]
    444         return aggregate(self, result)

ipdb> n
--Return--
None
> /usr/lib/python2.7/dist-packages/openerp/api.py(443)new_api()
    442     def new_api(self, *args, **kwargs):
--> 443         result = [method(rec, *args, **kwargs) for rec in self]
    444         return aggregate(self, result)

ipdb> n
AccessError: AccessEr...: read)')
> /usr/lib/python2.7/dist-packages/openerp/api.py(266)wrapper()
    265         if '_ids' in self.__dict__:
--> 266             return new_api(self, *args, **kwargs)
    267         else:

ipdb> n
--Return--
None
> /usr/lib/python2.7/dist-packages/openerp/api.py(266)wrapper()
    265         if '_ids' in self.__dict__:
--> 266             return new_api(self, *args, **kwargs)
    267         else:

ipdb> n
AccessError: AccessEr...: read)')
> /usr/lib/python2.7/dist-packages/openerp/fields.py(885)_compute_value()
    884             records.env.computed[field].update(records._ids)
--> 885         self.compute(records)
    886         for field in self.computed_fields:

ipdb> n
--Return--
None
> /usr/lib/python2.7/dist-packages/openerp/fields.py(885)_compute_value()
    884             records.env.computed[field].update(records._ids)
--> 885         self.compute(records)
    886         for field in self.computed_fields:

ipdb> n
AccessError: AccessEr...: read)')
> /usr/lib/python2.7/dist-packages/openerp/fields.py(893)compute_value()
    892             try:
--> 893                 self._compute_value(records)
    894             except (AccessError, MissingError):

ipdb> n
> /usr/lib/python2.7/dist-packages/openerp/fields.py(894)compute_value()
    893                 self._compute_value(records)
--> 894             except (AccessError, MissingError):
    895                 # some record is forbidden or missing, retry record by record

ipdb> p records
res.partner(489,)
ipdb> p self._compute_value(records)
*** AccessError: AccessError('AccessError', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: res.users, Operation: read)')
ipdb> p
`

**Comment by Deliveriya** [comment]
Fix 
```
diff -u res_partner.py.bug res_partner.py
--- res_partner.py.bug  2017-05-05 03:29:50.631889870 +0300
+++ res_partner.py      2017-05-08 21:47:21.356468826 +0300
@@ -90,9 +90,7 @@
         If one of those parameters is not set then reset the partner's
         geo_point and do not recompute it
         """
-        if not self.partner_latitude or not self.partner_longitude:
-            self.geo_point = False
-        else:
+        if self.partner_latitude and self.partner_longitude:
             self.geo_point = geo_fields.GeoPoint.from_latlon(
                 self.env.cr, self.partner_latitude, self.partner_longitude)

```

**Comment by yvaucher** [comment]
Thanks for the detailed tracing. In fact in a `api.depends` method, field value is reset anyway.

An other option would be to add `compute_sudo=True` on the field definition, but I'm struggling to find why would this computation requires extra rights with triggers.

**Comment by Deliveriya** [comment]
Ok.
If there will additional information, I will write.
Thanks you  for help.

**Comment by thomaspaulb** [comment]
Hey guys. I had a similar bug:

- In one of my custom modules I added an 8.0-style computed field on `res.partner` and added it on the customer form view as well as the customer tree view.
- Tree view worked fine, but when opening the customer form view the same `res.users` read AccessError appeared. This only in the case where logged in user has a different company selected than Administrator user.
- I debugged it down to a bug in Odoo whereby **if** the form contains some kind of reference to the 'Administrator' user (eg. Administrator is a follower or has some messages there), the AccessError for this is stored on `env.cache` and mostly forgotten about (not raised), **until** the new computed field starts to check for any triggers on the **inherited** models of `res.partner` (eg. `res.users`) and then [accessing what is in the cache about `res.users`](https://github.com/OCA/OCB/blob/8.0/openerp/fields.py#L1014), triggering a get() action on the `FailedValue` object that is there because of accessing the Administrator user, which then triggers the raise of the "sleeping" access error. 
- `odoo/odoo` as well as `OCA/OCB` exhibit this behaviour.
- [This issue](https://github.com/odoo/odoo/issues/6447) may be related. Possibly that one triggers on `res.partner` instead of `res.users` because of more strict security settings in the OP's access rule settings, disallowing access to the Administrator partner as well as his user.

I haven't been able to come up with a fix, but I do have a workaround: if the computed field is written as a v7-style computed field (which is the case for most of the built-in 8.0 computed fields anyway), the error does not occur.
