### ISSUE TITLE
[Bug] 9.0-ol3 branch: Openlayers is undefined on several places

### ISSUE THREAD

**Issue by dek-odoo** [OCA/geospatial#143]
When creating a wmts layer, javascript throws an error.
It says "Openlayers is undefined".
<b>Branch: 9.0-ol3</b>

>https://github.com/OCA/geospatial/blob/9.0-ol3/base_geoengine/static/src/js/views/geoengine_common.js#L51

>https://github.com/OCA/geospatial/blob/9.0-ol3/base_geoengine/static/src/js/views/geoengine_common.js#L56

Probably on some other places, too.

**Comment by dek-odoo** [comment]
@yvaucher

**Comment by yvaucher** [comment]
Thanks for reporting. I won't have the time yet to look deeper into this.

The branch 9.0-ol3 did not replace the 9.0 as not everything was tested.
In case you need to setup a wmts in Odoo 9.0 you might need to stick to the ol2 version. (in branch 9.0)

Otherwise can you try to replace `OpenLayers` by `ol` on those line. But the function name might have changed so it might not be enough.

**Comment by dek-odoo** [comment]
Ok, Thanks a lot for your reply.

I may need to stick with ol3 as it has some extra features.
I will try to fix the bug with what you said.
But I can create a PR with fix, if I could get some more info or hint on this.

Thank you.

**Comment by yvaucher** [comment]
My wild guess is that during migration from ol2 to ol3 those were not ported. And as the structure of ol3 changed a lot. Now we have to import ol instead of OpenLayers
