### ISSUE TITLE
base_geoengine_demo: javascript errors 

### ISSUE THREAD

**Issue by javi-ingeos** [OCA/geospatial#2]
[openerp 6.1 > base_geoengine_demo]

I am getting some javascript errors when accessing geoengine view and geo_edit_map widget

In geoengine view, when there is no record, I get:
- TypeError: f is undefined (firefox 30.0)
- Uncaught TypeError: Cannot read property 'attributes' of undefined (chrome 35.0, opera 22.0)

To reproduce on base_geoengine_demo:
- Open geoengine.demo.automatic.retailing.machine list view
- Delete all records
- Open geoengine view -> error

When I am editing a geo_point for the second time, I get:
- TypeError: a.layer is null (firefox 30.0)
- Uncaught TypeError: Cannot read property 'selectedFeatures' of null (chrome 35.0, opera 22.0)

To reproduce on base_geoengine_demo:
- Open geoengine.demo.automatic.retailing.machine list view
- Edit an existing record
- Select the point of the map and move it
- Save changes
- Click edit again
- Select the point -> error

**Comment by javi-ingeos** [comment]
Have we any news on this?

**Comment by javi-ingeos** [comment]
Have we any news on this?

**Comment by nbessi** [comment]
Hello, 

Please refer to issue  https://github.com/OCA/geospatial/issues/1
Due to lack of resources the project is actually in hibernation. We will accept and review any patch but 
as long there is no more contributor fix will probably not arrive. 

If you explicitly need a fix you can try to contact an OCA/Odoo partner to provide some help.

Regards

Nicolas
