### ISSUE TITLE
trace routes

### ISSUE THREAD

**Issue by jjlopezg** [OCA/geospatial#90]
Good morning, you can use google maps later?

I'm just a beginner as and I would like to draw routes between two points, where do I start?

Thank you

**Comment by yvaucher** [comment]
Hello @jjlopezg

No, google maps layer are not planned yet. If you are willing to contribute I will happily review it.
Otherwise, you should use openstreet map instead.

You will need to add a multilines field on your model:
https://github.com/OCA/geospatial/blob/9.0/base_geoengine/geo_multiline.py

The same way done here for Multi polygons: https://github.com/OCA/geospatial/blob/9.0/base_geoengine_demo/geo_npa.py#L36

Then define it in the view:
https://github.com/OCA/geospatial/blob/9.0/base_geoengine_demo/zip_view.xml#L14

And finally configure the layers you want for it.
